server.port : 8081
---
spring:
  profiles: local
---
spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: 192.168.0.103:9092, 192.168.0.103:9093, 192.168.0.103:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: 192.168.0.103:9092, 192.168.0.103:9093, 192.168.0.103:9094

---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer